# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" 
title                    : "Vignesh Sitaraman"
title_separator          : "-"
name                     : &name "Vignesh Sitaraman"
description              : &description "PhD Candidate in Experimental Nuclear Physics"
url                      : "https://vs19g.github.io" 
baseurl                  : "" 
repository               : "vs19g/vs19g.github.io"

# Site Author
author:
  avatar           : "profile.png" # Make sure to upload a photo named profile.png to /images/
  name             : "Vignesh Sitaraman"
  pronouns         : 
  bio              : "PhD Candidate specializing in experimental nuclear physics, detector construction, and digital DAQ systems."
  location         : "Tallahassee, FL"
  employer         : "Florida State University"
  uri              : 
  email            : "vsitaraman@fsu.edu" 

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=BjY0FunPZVgC&hl"
  orcid            : "https://orcid.org/0000-0002-5561-5286" # Update with your specific ORCID ID
  arxiv            : 
  researchgate     : 

  # Repositories and software development
  github           : "vs19g"
  stackoverflow    : 

  # Social media
  linkedin         : "vignesh-sitaraman-1b5a62136" # Double check your LinkedIn slug
  bluesky          : 
  twitter          : 

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser              : 
breadcrumbs         : false 
words_per_minute    : 160
future              : true
read_more           : "disabled" 
talkmap_link        : true      # Set to true to show your presentation locations

# Analytics
analytics:
  provider           : "false" 

# Collections (Research, Teaching, etc.)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
